# Generated by Django 4.0.5 on 2022-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Игра закончена')),
                ('is_jackpot', models.BooleanField(default=False, verbose_name='Джекпот выигран')),
                ('rolls', models.ManyToManyField(blank=True, to='roulette_main.roll', verbose_name='Спины раунда')),
            ],
        ),
    ]
